//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTest.SendTransactions {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pstalive.ipagoo.com", ConfigurationName="SendTransactions.SendTransactionsSoap")]
    public interface SendTransactionsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendCancelBollettinoBianco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.CancelledPaymentDTO SendCancelBollettinoBianco(string Username, string Password, string MemberCode, string TransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendFirstRequestBollettinoBianco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.PaymentVerifiedDTO SendFirstRequestBollettinoBianco(string Username, string Password, string MemberCode, WSTest.SendTransactions.BlankVerificationDTO dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendConfirmBollettinoBianco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.PaidSlipDTO SendConfirmBollettinoBianco(string Username, string Password, string MemberCode, string TransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendReverseBollettinoBianco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.ReversedPaymentDTO SendReverseBollettinoBianco(string Username, string Password, string MemberCode, string TransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendCancelBollettinoPrefilled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.CancelledPaymentDTO SendCancelBollettinoPrefilled(string Username, string Password, string MemberCode, string TransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendFirstRequestBollettinoPrefilled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.PaymentVerifiedDTO SendFirstRequestBollettinoPrefilled(string Username, string Password, string MemberCode, WSTest.SendTransactions.PrefilledVerificationDTO pv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendConfirmBollettinoPrefilled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.PaidSlipDTO SendConfirmBollettinoPrefilled(string Username, string Password, string MemberCode, string TransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendReverseBollettinoPrefilled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.ReversedPaymentDTO SendReverseBollettinoPrefilled(string Username, string Password, string MemberCode, string TransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendCancelPostePay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.CancelledTransactionDTO SendCancelPostePay(string Username, string Password, string MemberCode, string TransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendFirstRequestPostePay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.ConfirmPostePayIPPS SendFirstRequestPostePay(string Username, string Password, string MemberCode, WSTest.SendTransactions.VerifyUserDTO vu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendConfirmPostePay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.PaidPostePayIPPS SendConfirmPostePay(string Username, string Password, string MemberCode, string TransactionID, string Amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendCancelBollettino", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.CancelledPaymentDTO SendCancelBollettino(string Username, string Password, string MemberCode, string TransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendConfirmBollettino", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.PaidSlipIPPS SendConfirmBollettino(string Username, string Password, string MemberCode, string TransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pstalive.ipagoo.com/SendReverseBollettino", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasePaymentRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseResponse))]
        WSTest.SendTransactions.ReversedPaymentDTO SendReverseBollettino(string Username, string Password, string MemberCode, string TransactionID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class CancelledPaymentDTO : BasePaymentSlipResponse {
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReversedPaymentDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaidSlipDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentVerifiedDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelledPaymentDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public abstract partial class BasePaymentSlipResponse : BaseResponse {
        
        private string requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasePostepayResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelledTransactionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasePaymentSlipResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReversedPaymentDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaidSlipDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentVerifiedDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelledPaymentDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public abstract partial class BaseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class PaidSlipIPPS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string codeField;
        
        private string messageField;
        
        private string requestIdField;
        
        private int amountField;
        
        private string codUffPostaleField;
        
        private string sezUffPostaleField;
        
        private string uffVirtualeField;
        
        private string codStruPagField;
        
        private int dataAccettazioneField;
        
        private string progIncassoField;
        
        private int importoBollettinoField;
        
        private int commissioniAziendaField;
        
        private int commissioneAggiuntivaField;
        
        private string numBollettinoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CodUffPostale {
            get {
                return this.codUffPostaleField;
            }
            set {
                this.codUffPostaleField = value;
                this.RaisePropertyChanged("CodUffPostale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SezUffPostale {
            get {
                return this.sezUffPostaleField;
            }
            set {
                this.sezUffPostaleField = value;
                this.RaisePropertyChanged("SezUffPostale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UffVirtuale {
            get {
                return this.uffVirtualeField;
            }
            set {
                this.uffVirtualeField = value;
                this.RaisePropertyChanged("UffVirtuale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CodStruPag {
            get {
                return this.codStruPagField;
            }
            set {
                this.codStruPagField = value;
                this.RaisePropertyChanged("CodStruPag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int DataAccettazione {
            get {
                return this.dataAccettazioneField;
            }
            set {
                this.dataAccettazioneField = value;
                this.RaisePropertyChanged("DataAccettazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ProgIncasso {
            get {
                return this.progIncassoField;
            }
            set {
                this.progIncassoField = value;
                this.RaisePropertyChanged("ProgIncasso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int ImportoBollettino {
            get {
                return this.importoBollettinoField;
            }
            set {
                this.importoBollettinoField = value;
                this.RaisePropertyChanged("ImportoBollettino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int CommissioniAzienda {
            get {
                return this.commissioniAziendaField;
            }
            set {
                this.commissioniAziendaField = value;
                this.RaisePropertyChanged("CommissioniAzienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int CommissioneAggiuntiva {
            get {
                return this.commissioneAggiuntivaField;
            }
            set {
                this.commissioneAggiuntivaField = value;
                this.RaisePropertyChanged("CommissioneAggiuntiva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string NumBollettino {
            get {
                return this.numBollettinoField;
            }
            set {
                this.numBollettinoField = value;
                this.RaisePropertyChanged("NumBollettino");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class PaidPostePayIPPS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string codeField;
        
        private string messageField;
        
        private string requestIdField;
        
        private int amountField;
        
        private string codUffPostaleField;
        
        private string sezUffPostaleField;
        
        private string uffVirtualeField;
        
        private string codStruPagField;
        
        private int dataAccettazioneField;
        
        private string progIncassoField;
        
        private int importoBollettinoField;
        
        private int commissioniAziendaField;
        
        private int commissioneAggiuntivaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CodUffPostale {
            get {
                return this.codUffPostaleField;
            }
            set {
                this.codUffPostaleField = value;
                this.RaisePropertyChanged("CodUffPostale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SezUffPostale {
            get {
                return this.sezUffPostaleField;
            }
            set {
                this.sezUffPostaleField = value;
                this.RaisePropertyChanged("SezUffPostale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UffVirtuale {
            get {
                return this.uffVirtualeField;
            }
            set {
                this.uffVirtualeField = value;
                this.RaisePropertyChanged("UffVirtuale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CodStruPag {
            get {
                return this.codStruPagField;
            }
            set {
                this.codStruPagField = value;
                this.RaisePropertyChanged("CodStruPag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int DataAccettazione {
            get {
                return this.dataAccettazioneField;
            }
            set {
                this.dataAccettazioneField = value;
                this.RaisePropertyChanged("DataAccettazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ProgIncasso {
            get {
                return this.progIncassoField;
            }
            set {
                this.progIncassoField = value;
                this.RaisePropertyChanged("ProgIncasso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int ImportoBollettino {
            get {
                return this.importoBollettinoField;
            }
            set {
                this.importoBollettinoField = value;
                this.RaisePropertyChanged("ImportoBollettino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int CommissioniAzienda {
            get {
                return this.commissioniAziendaField;
            }
            set {
                this.commissioniAziendaField = value;
                this.RaisePropertyChanged("CommissioniAzienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int CommissioneAggiuntiva {
            get {
                return this.commissioneAggiuntivaField;
            }
            set {
                this.commissioneAggiuntivaField = value;
                this.RaisePropertyChanged("CommissioneAggiuntiva");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class ConfirmPostePayIPPS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string codeField;
        
        private string messageField;
        
        private string requestIdField;
        
        private int maxTopUpValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int MaxTopUpValue {
            get {
                return this.maxTopUpValueField;
            }
            set {
                this.maxTopUpValueField = value;
                this.RaisePropertyChanged("MaxTopUpValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class CardHolderDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string taxIdCodeField;
        
        private string addressField;
        
        private string address2Field;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string mobilePhoneField;
        
        private string emailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TaxIdCode {
            get {
                return this.taxIdCodeField;
            }
            set {
                this.taxIdCodeField = value;
                this.RaisePropertyChanged("TaxIdCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("MobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class CustomerDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string taxIdCodeField;
        
        private string addressField;
        
        private string address2Field;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string countryField;
        
        private string mobilePhoneField;
        
        private string emailAddressField;
        
        private string identityDocumentIdField;
        
        private System.Nullable<System.DateTime> documentExpireDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TaxIdCode {
            get {
                return this.taxIdCodeField;
            }
            set {
                this.taxIdCodeField = value;
                this.RaisePropertyChanged("TaxIdCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("MobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string IdentityDocumentId {
            get {
                return this.identityDocumentIdField;
            }
            set {
                this.identityDocumentIdField = value;
                this.RaisePropertyChanged("IdentityDocumentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> DocumentExpireDate {
            get {
                return this.documentExpireDateField;
            }
            set {
                this.documentExpireDateField = value;
                this.RaisePropertyChanged("DocumentExpireDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class PayerDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string addressField;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string stateOrProvinceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                this.stateOrProvinceField = value;
                this.RaisePropertyChanged("StateOrProvince");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerifyUserDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseVerification))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrefilledVerificationDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BlankVerificationDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class BasePaymentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SourceIP {
            get {
                return this.sourceIPField;
            }
            set {
                this.sourceIPField = value;
                this.RaisePropertyChanged("SourceIP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class VerifyUserDTO : BasePaymentRequest {
        
        private CustomerDTO customerField;
        
        private CardHolderDTO cardHolderField;
        
        private string cardNumberField;
        
        private decimal amountField;
        
        private string currencyField;
        
        private string productCodeField;
        
        private PaymentType paymentTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CustomerDTO Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CardHolderDTO CardHolder {
            get {
                return this.cardHolderField;
            }
            set {
                this.cardHolderField = value;
                this.RaisePropertyChanged("CardHolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("CardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public PaymentType PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("PaymentType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public enum PaymentType {
        
        /// <remarks/>
        Any,
        
        /// <remarks/>
        Cash,
        
        /// <remarks/>
        DebitCard,
        
        /// <remarks/>
        CreditCard,
        
        /// <remarks/>
        Mixed,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrefilledVerificationDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BlankVerificationDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class BaseVerification : BasePaymentRequest {
        
        private PostalSlipModel typeField;
        
        private string accountNumField;
        
        private decimal amountField;
        
        private System.DateTime requestDateField;
        
        private PayerDTO payerField;
        
        private PaymentType paymentTypeField;
        
        private string currencyField;
        
        private string productCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PostalSlipModel Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccountNum {
            get {
                return this.accountNumField;
            }
            set {
                this.accountNumField = value;
                this.RaisePropertyChanged("AccountNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public PayerDTO Payer {
            get {
                return this.payerField;
            }
            set {
                this.payerField = value;
                this.RaisePropertyChanged("Payer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public PaymentType PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("PaymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public enum PostalSlipModel {
        
        /// <remarks/>
        Any,
        
        /// <remarks/>
        TD896,
        
        /// <remarks/>
        TD674,
        
        /// <remarks/>
        TD123,
        
        /// <remarks/>
        TD451,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class PrefilledVerificationDTO : BaseVerification {
        
        private string paymentSlipNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PaymentSlipNum {
            get {
                return this.paymentSlipNumField;
            }
            set {
                this.paymentSlipNumField = value;
                this.RaisePropertyChanged("PaymentSlipNum");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class BlankVerificationDTO : BaseVerification {
        
        private string accountHolderField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountHolder {
            get {
                return this.accountHolderField;
            }
            set {
                this.accountHolderField = value;
                this.RaisePropertyChanged("AccountHolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelledTransactionDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public abstract partial class BasePostepayResponse : BaseResponse {
        
        private string requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class CancelledTransactionDTO : BasePostepayResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class ReversedPaymentDTO : BasePaymentSlipResponse {
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class PaidSlipDTO : BasePaymentSlipResponse {
        
        private decimal amountField;
        
        private decimal feeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
                this.RaisePropertyChanged("Fee");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pstalive.ipagoo.com")]
    public partial class PaymentVerifiedDTO : BasePaymentSlipResponse {
        
        private decimal amountField;
        
        private decimal feesField;
        
        private string transactionIDField;
        
        private string accountNumField;
        
        private string accountHolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Fees {
            get {
                return this.feesField;
            }
            set {
                this.feesField = value;
                this.RaisePropertyChanged("Fees");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AccountNum {
            get {
                return this.accountNumField;
            }
            set {
                this.accountNumField = value;
                this.RaisePropertyChanged("AccountNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AccountHolder {
            get {
                return this.accountHolderField;
            }
            set {
                this.accountHolderField = value;
                this.RaisePropertyChanged("AccountHolder");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendTransactionsSoapChannel : WSTest.SendTransactions.SendTransactionsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendTransactionsSoapClient : System.ServiceModel.ClientBase<WSTest.SendTransactions.SendTransactionsSoap>, WSTest.SendTransactions.SendTransactionsSoap {
        
        public SendTransactionsSoapClient() {
        }
        
        public SendTransactionsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendTransactionsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendTransactionsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendTransactionsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WSTest.SendTransactions.CancelledPaymentDTO SendCancelBollettinoBianco(string Username, string Password, string MemberCode, string TransactionID) {
            return base.Channel.SendCancelBollettinoBianco(Username, Password, MemberCode, TransactionID);
        }
        
        public WSTest.SendTransactions.PaymentVerifiedDTO SendFirstRequestBollettinoBianco(string Username, string Password, string MemberCode, WSTest.SendTransactions.BlankVerificationDTO dt) {
            return base.Channel.SendFirstRequestBollettinoBianco(Username, Password, MemberCode, dt);
        }
        
        public WSTest.SendTransactions.PaidSlipDTO SendConfirmBollettinoBianco(string Username, string Password, string MemberCode, string TransactionID) {
            return base.Channel.SendConfirmBollettinoBianco(Username, Password, MemberCode, TransactionID);
        }
        
        public WSTest.SendTransactions.ReversedPaymentDTO SendReverseBollettinoBianco(string Username, string Password, string MemberCode, string TransactionID) {
            return base.Channel.SendReverseBollettinoBianco(Username, Password, MemberCode, TransactionID);
        }
        
        public WSTest.SendTransactions.CancelledPaymentDTO SendCancelBollettinoPrefilled(string Username, string Password, string MemberCode, string TransactionID) {
            return base.Channel.SendCancelBollettinoPrefilled(Username, Password, MemberCode, TransactionID);
        }
        
        public WSTest.SendTransactions.PaymentVerifiedDTO SendFirstRequestBollettinoPrefilled(string Username, string Password, string MemberCode, WSTest.SendTransactions.PrefilledVerificationDTO pv) {
            return base.Channel.SendFirstRequestBollettinoPrefilled(Username, Password, MemberCode, pv);
        }
        
        public WSTest.SendTransactions.PaidSlipDTO SendConfirmBollettinoPrefilled(string Username, string Password, string MemberCode, string TransactionID) {
            return base.Channel.SendConfirmBollettinoPrefilled(Username, Password, MemberCode, TransactionID);
        }
        
        public WSTest.SendTransactions.ReversedPaymentDTO SendReverseBollettinoPrefilled(string Username, string Password, string MemberCode, string TransactionID) {
            return base.Channel.SendReverseBollettinoPrefilled(Username, Password, MemberCode, TransactionID);
        }
        
        public WSTest.SendTransactions.CancelledTransactionDTO SendCancelPostePay(string Username, string Password, string MemberCode, string TransactionID) {
            return base.Channel.SendCancelPostePay(Username, Password, MemberCode, TransactionID);
        }
        
        public WSTest.SendTransactions.ConfirmPostePayIPPS SendFirstRequestPostePay(string Username, string Password, string MemberCode, WSTest.SendTransactions.VerifyUserDTO vu) {
            return base.Channel.SendFirstRequestPostePay(Username, Password, MemberCode, vu);
        }
        
        public WSTest.SendTransactions.PaidPostePayIPPS SendConfirmPostePay(string Username, string Password, string MemberCode, string TransactionID, string Amount) {
            return base.Channel.SendConfirmPostePay(Username, Password, MemberCode, TransactionID, Amount);
        }
        
        public WSTest.SendTransactions.CancelledPaymentDTO SendCancelBollettino(string Username, string Password, string MemberCode, string TransactionID) {
            return base.Channel.SendCancelBollettino(Username, Password, MemberCode, TransactionID);
        }
        
        public WSTest.SendTransactions.PaidSlipIPPS SendConfirmBollettino(string Username, string Password, string MemberCode, string TransactionID) {
            return base.Channel.SendConfirmBollettino(Username, Password, MemberCode, TransactionID);
        }
        
        public WSTest.SendTransactions.ReversedPaymentDTO SendReverseBollettino(string Username, string Password, string MemberCode, string TransactionID) {
            return base.Channel.SendReverseBollettino(Username, Password, MemberCode, TransactionID);
        }
    }
}
